### ISSUE TITLE
Nelmio's api/doc is inaccessible without authentication

### ISSUE THREAD

**Issue by kochen** [jorge07/ddd-playground#24]
Authentication is required to view Nelmio's Documentation @ `api/doc`:
```
{
code: 401,
message: "JWT Token not found"
}
```

Even though a `api:doc:dump` is being made by the `build.xml` it would be a good idea to allow access to the the docs without authentication.

**Comment by jorge07** [comment]
Ops, you're right. I changed now https://github.com/jorge07/ddd-playground/commit/b6cd8d62e34e88da05858e65cfab69e0ba7086ad but i did it with the phone and I didnt test it. If doesnt work I'll test it tomorow morning. Now the endpoint should be `/api-doc`

Thanks

**Comment by kochen** [comment]
While this is probably a working solution, I think a better one would be to adjust the `security.yml` so that `/api/doc` (the most commonly used URL) doesn't require authentication.

**Comment by jorge07** [comment]
I finally found time to fix it: https://github.com/jorge07/ddd-playground/commit/0ec659813c7f834f81ced64ab74931c35846128a

Feel free to close if looks good to you.

**Comment by kochen** [comment]
Didn't have time to test be logically it looks much better 👍
