### ISSUE TITLE
Empty response upon user registration

### ISSUE THREAD

**Issue by kochen** [jorge07/ddd-playground#27]
The `auth/register` (in the SecurityController) redirects and returns the response from `get_user` (in the UserController) [- Shouldn't this be decoupled?]

But the response is empty:
![image](https://cloud.githubusercontent.com/assets/106042/24857770/c37ddcba-1de9-11e7-88a5-bbd6f04030cd.png)

**Comment by jorge07** [comment]
If you open `Response Headers -> [Expand]` you'll see a `location` header with the `get_user` url

**Comment by kochen** [comment]
You are correct :)

I had in my head a use case where you create a user from a mobile app (i.e) and then you would require an extra call to see you own profile...

**Comment by jorge07** [comment]
Well you can set true the `followRedirects` on the `HttpClient` and that's it

**Comment by kochen** [comment]
@jorge07 Using the `Location` in a `register` flow doesn't make much sense.
The user at the end of this call is not logged in and doesn't even have a `token`, so he **must** `login` for that.

What would be your proposed flow here?

**Comment by jorge07** [comment]
When you create a user you not need to login it always. 

For example: A backOffice where hhrr create accounts for the new employers and/or you wanna validate the user email sending a token to the user inbox. 

The case you say is a common case and I use to create another command like `registerAndAutologin` (*ubiquitous language*):

```
class RegisterUserAndAutologinHandler
{
    /**
     * @var Factory
     */
    private $factory;
    /**
     * @var UserRepository
     */
    private $repository;
    /**
     * @var JWTManager
     */
    private $JWTManager;

    public function __construct(Factory $factory, UserRepository $repository, JWTManager $JWTManager)
    {
        $this->factory = $factory;
        $this->repository = $repository;
        $this->JWTManager = $JWTManager;
    }

    public function handle(RegisterUserAndAutologinRequest $request): array
    {
        $user = $this->factory->register($request->toForm());

        $this->repository->store($user);

        return [
            'token' => $this->JWTManager->create(new AuthenticatedUser($user))
        ];
    }
}
```

Or even easier call using the bus the existing commands.

**Comment by kochen** [comment]
@jorge07 thanks, makes sense.
except that now you are coupling it to a `command_bus` that actually returns something, and even specified in it the response format.

**Comment by jorge07** [comment]
Whats your proposal?

**Comment by kochen** [comment]
That's a good question, no real proposal here.
but what I'm looking is something closer to real-life usage:
`Login` = `get_token` + `get_user`
`Register` = `create_user` + `Login` (above)

So basically after Login returns the right data, I'd call/redirect from `Register` to `Login`.

make sense?

**Comment by jorge07** [comment]
Well, following the specs:

```
RFC 2616                        HTTP/1.1                       June 1999

   If a resource has been created on the origin server, the response
   SHOULD be 201 (Created) and contain an entity which describes the
   status of the request and refers to the new resource, and a Location
   header (see section 14.30).
```
You should return the resource created, not another thing like the token.
(note also that spec say you should return the resource on the body I'm not doing it)

The `auth/register` endpoint should only do that to don't broke *single responsibility* principe. If your user flow require auto-login, it's not this case; it can be done with a custom endpoint like the `example` in the previous comment -> https://github.com/jorge07/ddd-playground/issues/27#issuecomment-292950278.

Note also that the JWT contains useful information like username or email to avoid recall the API by the client side.

**Comment by kochen** [comment]
Returning the resource on the body, was exactly my point in the beginning of this issue.

Think about a situation where the user logs in and out and a different user logs in (from same device/computer), you would have to make another `GET` to change the newly logged in User's profile data (i.e avatar), so it could refresh the local storage data.
Maybe as a all-in-one solution the User resource could be returned in the body, and the token in the Header?

**Comment by jorge07** [comment]
Return the user resource on the `auth/register` endpoint make sense to me.

But not in `login`, this information can be stored in the JWT token [see here](https://github.com/jorge07/ddd-playground/blob/master/src/Infrastructure/SecurityBundle/EventListener/JWTCreatedListener.php#L22).

**Comment by kochen** [comment]
yes I understand.
It'd just require doing an extra `GET` for `view_(own)_profile`, which could be avoided.

**Comment by jorge07** [comment]
Hey @kochen this issue has been here for too long so I created a PR #34 with the fix and also some improvements to parallelise the tests and migrated to Jenkins. Can you have a look?
