### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by onlyshow** [jorge07/ddd-playground#38]
`docker-compose -f etc/infrastructure/dev/docker-compose.yml exec fpm bin/console rabbitmq:multiple-consumer events`
`ERROR: .IOError: [Errno 2] No such file or directory: u'.\\etc/infrastructure/dev/docker-compose.yml'`

**Comment by jorge07** [comment]
Hi @onlyshow are you executing this in the root of the project?

I just tested and looks working:

```
$ docker-compose -f etc/infrastructure/dev/docker-compose.yml up -d                                                           
Creating dev_rmq_1           ... done
Creating dev_redis_1         ... done
Creating dev_kibana_1        ... done
Creating dev_elasticsearch_1 ... done
Creating dev_mysql_1         ... done
Creating dev_fpm_1           ... done
Creating dev_nginx_1         ... done

$ docker-compose -f etc/infrastructure/dev/docker-compose.yml exec fpm sh -c './bin/console rabbitmq:multiple-consumer events'
```

**Comment by onlyshow** [comment]
![tim 20180125102710](https://user-images.githubusercontent.com/12505832/35367647-71876876-01ba-11e8-894b-82d1f3c3e7fa.png)

![tim 20180125102352](https://user-images.githubusercontent.com/12505832/35367555-df0e4dfc-01b9-11e8-9ad1-0e2190d74584.png)
@jorge07

**Comment by jorge07** [comment]
Seems you're using windows, and paths needs to by adapted, try:

`docker-compose -f etc\infrastructure\dev\docker-compose.yml up -d`

`docker-compose -f etc\infrastructure\dev\docker-compose.yml exec fpm sh -c './bin/console rabbitmq:multiple-consumer events'`

**Comment by onlyshow** [comment]
i'm use `php /bin/console rabbitmq:multiple-consumer events`
success, but no daemon, is right?

**Comment by jorge07** [comment]
Right
