### ISSUE TITLE
no database?

### ISSUE THREAD

**Issue by onlyshow** [jorge07/ddd-playground#39]
Learn and use the document

**Comment by jorge07** [comment]
Hi @onlyshow I don't know what do you want to say with `Learn and use the document`. 

The database engine is defined in the docker-compose but of course not the schema.
To setup the schema there's a ant task that you can run inside the php container:

`ant createdatabase`

**Comment by onlyshow** [comment]
i'm use `php bin/console doctrine:schema:create`
get dateabse tables.
Project USES a lot of I didn't contact with procedures, can you write a brief tutorial, thank you!

**Comment by onlyshow** [comment]
![tim 20180126112337](https://user-images.githubusercontent.com/12505832/35423914-76682a8e-028b-11e8-82a2-4a086b9d6a16.png)

**Comment by jorge07** [comment]
Add a setup step in the Readme may help to prevent things like that. Can you drop me few lines about your main problems? I'll try to work this weekend in add to the Readme some setup documentation

**Comment by onlyshow** [comment]
use`ant`build,Solved the problem.
But, still want to a complete introduction of project.
thanks.

**Comment by jorge07** [comment]
I added some setup doc to the readme. Feel free to reopen if you need more information there. Thanks!
