### ISSUE TITLE
User model uses ArrayCollection

### ISSUE THREAD

**Issue by mqxim** [jorge07/ddd-playground#45]
I noticed that User domain model has aggregation with Doctrine Array Collections, does not it violates DDD principles? We should create interface for collection in domain common bundle and the adapter for ArrayCollection in infrastrucutre layer, should not we?

**Comment by aswierc** [comment]
I did, that what you talked about - I created the interface for collection in the domain, and next to I created, for example, myCollection in infra, 'extends ArrayCollection implements MyInterfaceFromDomain'. 

👍

**Comment by jorge07** [comment]
You're totally right here. This is a trade off. My models are also my DB schema. And it doesn't have to be like that. When I did the project thought that decouple until the infinite wasn't worth it the time I've to spend. We're paid to deliver anyway. After some years I've to say that you can couple to a very trusted library if the api is stable and the building and maintenance time of the opposite is too much. In the other hand, your domain model doesn't care about your DB scheme or the DB itself so projections are a game changer
To accomplish this generate projections by collecting domain events, like I do here https://github.com/jorge07/symfony-4-es-cqrs-boilerplate/blob/master/src/Infrastructure/User/Query/Projections/UserView.php
Event Sourcing is optional BTW.
I hope you find this helpful
